name: Scan Songs

on:
  push:
    branches:
      - main    
  workflow_dispatch:

permissions: write-all

jobs:
  fetch_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit changes to submodule
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update submodule

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Run scan
        run: python scan.py

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git add encore.json
          git add covers/*
          git commit -m "Update Songs"
          git push